# -*- coding: utf-8 -*-
"""Skin_Cancer_Detection.ipynb

Automatically generated by Colab.

"""

import pathlib
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import PIL
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

from google.colab import drive
drive.mount('/content/drive')

# Defining the path for train and test images
from pathlib import Path
## Todo: Update the paths of the train and test dataset

data_dir_train = "/content/drive/MyDrive/Colab_Notebooks/SkinCancer_ISIC_Data/Train"
data_dir_test = "/content/drive/MyDrive/Colab_Notebooks/SkinCancer_ISIC_Data/Test"

os.listdir(data_dir_train)

os.listdir(data_dir_test)

import glob
image_count_train = len(glob.glob(data_dir_train + "/**/*.jpg"))
print(image_count_train)
#image_count_train = len(list(data_dir_train.glob('*/*.jpg')))
#print(image_count_train)
image_count_test = len(glob.glob(data_dir_test + "/**/*.jpg"))
print(image_count_test)

"""**Load using keras.preprocessing**"""

batch_size = 32
img_height = 180
img_width = 180

!python --version

!pip install tensorflow_datasets

from tensorflow.keras.utils import image_dataset_from_directory

# @title Training DataSet
## Write your train dataset here
## Note use seed=123 while creating your dataset using tf.keras.preprocessing.image_dataset_from_directory
## Note, make sure your resize your images to the size img_height*img_width, while writting the dataset
#train_ds = ##todo
#data_train =
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
  data_dir_train,
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size,
  validation_split=0.2,
  subset= 'training')

# @title Visualize distribution of classes in the training dataset.
def class_distribution_count(directory):

    #count number of image in each classes
    count= []
    for path in pathlib.Path(directory).iterdir():
        if path.is_dir():
            count.append(len([name for name in os.listdir(path)
                               if os.path.isfile(os.path.join(path, name))]))

    #name of the classes
    sub_directory = [name for name in os.listdir(directory)
                    if os.path.isdir(os.path.join(directory, name))]

    #return dataframe with image count and class.
    return pd.DataFrame(list(zip(sub_directory,count)),columns =['Class', 'No. of Image'])

df = class_distribution_count(data_dir_train)
df

## Write your validation dataset here
## Note use seed=123 while creating your dataset using tf.keras.preprocessing.image_dataset_from_directory
## Note, make sure your resize your images to the size img_height*img_width, while writting the dataset
val_ds =  tf.keras.preprocessing.image_dataset_from_directory(
  data_dir_train,
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size,
  validation_split=0.2,
  subset= 'validation'
)

# List out all the classes of skin cancer and store them in a list.
# You can find the class names in the class_names attribute on these datasets.
# These correspond to the directory names in alphabetical order.
class_names = train_ds.class_names
print(class_names)

"""**Visualize the data
Todo, create a code to visualize one instance of all the nine classes present in the dataset**
"""

import matplotlib.pyplot as plt

### your code goes here, you can use training or validation data to visualize
plt.figure(figsize=(10, 10))
for images, labels in train_ds.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[labels[i]])
        plt.axis("off")

AUTOTUNE = tf.data.experimental.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

"""**Create the model
Todo: Create a CNN model, which can accurately detect 9 classes present in the dataset. Use layers.experimental.preprocessing.Rescaling to normalize pixel values between (0,1). The RGB channel values are in the [0, 255] range. This is not ideal for a neural network. Here, it is good to standardize values to be in the [0, 1]**
"""

import tensorflow as tf
from tensorflow.keras import layers, models

input_shape = (img_height, img_width, 3)

model = models.Sequential()

# First Convolutional Layer
model.add(layers.Rescaling(1./255, input_shape=input_shape))  # Correct way to use Rescaling layer
model.add(layers.Conv2D(32, kernel_size=(3,3), activation='relu'))  #feature extraction
model.add(layers.MaxPool2D(pool_size=(2,2)))  #retain important info

# Second Convolutional Layer
model.add(layers.Conv2D(64, kernel_size=(3,3), activation='relu'))
model.add(layers.MaxPool2D(pool_size=(2,2)))

# Third Convolutional Layer
model.add(layers.Conv2D(128, kernel_size=(3,3), activation='relu'))
model.add(layers.MaxPool2D(pool_size=(2,2)))

# Flatten layer
model.add(layers.Flatten())  # Flattening the multi-dimensional input into a single dimension.

# Dense Layer
model.add(layers.Dense(128, activation='relu'))  #decision making

# Output layer with softmax activation
model.add(layers.Dense(len(class_names), activation='softmax'))  # Assuming class_names is defined elsewhere

len(class_names)

### Todo, choose an appropirate optimiser and loss function
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# View the summary of all layers
model.summary()

from tensorflow.keras.utils import plot_model
plot_model(model,to_file='model_plot.png',show_shapes=True, show_layer_names=True)

epochs = 10
history = model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=epochs
)

"""# **Visualizing Training Results**"""

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""Todo: Write your findings after the model fit, see if there is an evidence of model overfit or underfit

# **Write your findings here**
"""

# Todo, after you have analysed the model fit history for presence of underfit or overfit, choose an appropriate data augumentation strategy.
#As the training accuracy(92.35%)  is higher than validation accuracy(53.47%), it is an indication of overfitting. It means model is verfitting to the traing data.
# Your code goes here
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define data augmentation parameters
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

# Todo, visualize how your augmentation strategy works for one instance of training image.
# Your code goes here
# Load a sample training image
from keras.preprocessing import image
from tensorflow.keras.preprocessing.image import load_img, img_to_array
img_path= "/content/drive/MyDrive/Colab_Notebooks/SkinCancer_ISIC_Data/Train/nevus/ISIC_0000019.jpg"
img = image.load_img(img_path, target_size=(150, 150))  # Adjust target size as needed
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)

plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.imshow(img)
plt.title('Original Image')

# Apply augmentation transformations
i = 0
for batch in datagen.flow(x, batch_size=1):
    plt.subplot(1, 2, 2)
    plt.imshow(image.array_to_img(batch[0]))
    plt.title('Augmented Image')
    plt.axis('off')
    i += 1
    if i >= 1:  # Number of augmentation instances to generate
        break  # Break the loop to prevent infinite generation

plt.tight_layout()
plt.show()

"""# Todo:
# **Create the model, compile and train the model**
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

input_shape = (img_height, img_width, 3)

data_augmentation = keras.Sequential([
    # Randomly flip each image horizontally and vertically
    layers.RandomFlip("horizontal_and_vertical"),

    # Randomly rotate each image
    layers.RandomRotation(0.2),

    # Randomly zoom each image during training
    layers.RandomZoom(0.2),

    # Randomly translate each image during training
    layers.RandomTranslation(0.1, 0.1)
])

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

input_shape = (img_height, img_width, 3)

model2 = Sequential()

# Augmentation Layer
model2.add(data_augmentation)

# ✅ Corrected Rescaling Layer (Removed `experimental.preprocessing`)
model2.add(layers.Rescaling(1./255, input_shape=input_shape))

# First Convolution Layer
model2.add(layers.Conv2D(32, kernel_size=(3,3), activation='relu'))
model2.add(layers.MaxPool2D(pool_size=(2,2)))
model2.add(layers.Dropout(0.25))

# Second Convolution Layer
model2.add(layers.Conv2D(64, kernel_size=(3,3), activation='relu'))
model2.add(layers.MaxPool2D(pool_size=(2,2)))
model2.add(layers.Dropout(0.25))

# Third Convolution Layer
model2.add(layers.Conv2D(128, kernel_size=(3,3), activation='relu'))
model2.add(layers.MaxPool2D(pool_size=(2,2)))

# Flatten Layer
model2.add(layers.Flatten())

# Dense Layers
model2.add(layers.Dense(128, activation='relu'))
model2.add(layers.Dropout(0.50))

# Output Layer with Softmax
model2.add(layers.Dense(len(class_names), activation='softmax'))

"""# **Compiling the model**"""

## Your code goes here
from tensorflow.keras.callbacks import ReduceLROnPlateau
learn_control = ReduceLROnPlateau(monitor='val_accuracy', patience=5,
                                  verbose=1,factor=0.2, min_lr=1e-7)
opt=tf.keras.optimizers.Adam()
model2.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  # Use categorical crossentropy for multi-class classification
              optimizer=opt,
              metrics=['accuracy'],run_eagerly=True)

"""# **Training the model**"""

##Your code goes here, note: train your model for 20 epochs
epochs=10
history = model2.fit(train_ds,epochs=epochs,validation_data=val_ds)

"""# **Visualizing the results**"""

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

model2.summary()

from tensorflow.keras.utils import plot_model
plot_model(model2,to_file='model2_plot.png',show_shapes=True, show_layer_names=True)

"""# **Todo: Write your findings after the model fit, see if there is an evidence of model overfit or underfit. Do you think there is some improvement now as compared to the previous model run?**

# **Todo: Find the distribution of classes in the training dataset.**

# Context: Many times real life datasets can have class imbalance, one class can have proportionately higher number of samples compared to the others. Class imbalance can have a detrimental effect on the final model quality. Hence as a sanity check it becomes important to check what is the distribution of classes in the data.
"""

# @title Class Imbalance Detection
## Your code goes here.
def class_distribution_count(directory):

    #count number of image in each classes
    count= []
    for path in pathlib.Path(directory).iterdir():
        if path.is_dir():
            count.append(len([name for name in os.listdir(path)
                               if os.path.isfile(os.path.join(path, name))]))

    #name of the classes
    sub_directory = [name for name in os.listdir(directory)
                    if os.path.isdir(os.path.join(directory, name))]

    #return dataframe with image count and class.
    return pd.DataFrame(list(zip(sub_directory,count)),columns =['Class', 'No. of Image'])

df = class_distribution_count(data_dir_train)
df

#Visualize the Number of image in each class.
import seaborn as sns
plt.figure(figsize=(10, 8))
sns.barplot(x="No. of Image", y="Class", data=df,
            label="Class")

"""## **Todo :** Write your findings here:
- Which class has the least number of samples?
- Seborrheic Keratosis has least number of samples.
- Which classes dominate the data in terms proportionate number of samples?
- Pigmented benign keratosis

## **Todo :** Rectify the class imbalance

## **Context** You can use a python package known as Augmentor (https://augmentor.readthedocs.io/en/master/) to add more samples across all classes so that none of the classes have very few samples.

To rectify class imbalance, we will use Augmentor and add 500 samples across all classes.
"""

!pip install Augmentor

path_to_training_dataset="/content/drive/MyDrive/Colab_Notebooks/SkinCancer_ISIC_Data/Train/"
import Augmentor
for i in class_names:
    p = Augmentor.Pipeline(path_to_training_dataset + i)
    p.rotate(probability=0.7, max_left_rotation=10, max_right_rotation=10)
    p.sample(500) ## We are adding 500 samples per class to make sure that none of the classes are sparse.

import glob
image_count_train = len(glob.glob(data_dir_train + "/**/output/*.jpg"))
print(image_count_train)
#image_count_train = len(list(data_dir_train.glob('*/output/*.jpg')))
#print(image_count_train)

"""# **Lets see the distribution of augmented data after adding new images to the original training data.**"""

path_list = [x for x in glob.glob(os.path.join(data_dir_train, '**','output', '*.jpg'))]
path_list

lesion_list_new = [os.path.basename(os.path.dirname(os.path.dirname(y))) for y in glob.glob(os.path.join(data_dir_train, '**','output', '*.jpg'))]
lesion_list_new

dataframe_dict_new = dict(zip(path_list, lesion_list_new))

df2 = pd.DataFrame(list(dataframe_dict_new.items()),columns = ['Path','Label'])
#new_df = original_df.append(df2)

new_df=df2

new_df['Label'].value_counts()

"""## **Todo :**  Train the model on the data created using Augmentor"""

batch_size = 32
img_height = 180
img_width = 180

"""## **Todo :** Create a training dataset"""

data_dir_train="/content/drive/MyDrive/Colab_Notebooks/SkinCancer_ISIC_Data/Train/"
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
  data_dir_train,
  seed=123,
validation_split = 0.2,
subset = "training",  # Choose the correct parameter value to refer only to training data
image_size =(img_height, img_width),
#label_mode='categorical',
batch_size=batch_size)

"""## **Todo :** Create a validation dataset"""

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
  data_dir_train,
  seed=123,
  validation_split = 0.2,
  subset = "validation",## Todo choose the correct parameter value, so that only validation data is refered to,
  image_size=(img_height, img_width),
  #label_mode='categorical',
  batch_size=batch_size)

"""## **Todo :** Create your model (make sure to include normalization)"""

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Rescaling, Conv2D, MaxPool2D, Dropout, Flatten, Dense

# Define input shape
input_shape = (img_height, img_width, 3)

# Model Definition
model3 = Sequential()

# Rescaling Layer
model3.add(Rescaling(1./255, input_shape=input_shape))

# First Convolutional Layer
model3.add(Conv2D(32, kernel_size=(2,2), activation='relu'))
model3.add(MaxPool2D(pool_size=(2,2)))
model3.add(Dropout(0.25))

# Second Convolutional Layer
model3.add(Conv2D(64, kernel_size=(2,2), activation='relu'))
model3.add(MaxPool2D(pool_size=(2,2)))
model3.add(Dropout(0.25))

# Third Convolutional Layer
model3.add(Conv2D(128, kernel_size=(2,2), activation='relu'))
model3.add(MaxPool2D(pool_size=(2,2)))

# Flatten Layer
model3.add(Flatten())

# Dense Layer
model3.add(Dense(128, activation='relu'))

# Dropout Layer
model3.add(Dropout(0.50))

# Output Layer
model3.add(Dense(len(class_names), activation='softmax'))

"""## **Todo :** Compile your model (Choose optimizer and loss function appropriately)"""

opt=tf.keras.optimizers.Adam()
model3.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),  # Use categorical crossentropy for multi-class classification
              optimizer=opt,
              metrics=['accuracy'],run_eagerly=True)

model3.summary()

from tensorflow.keras.utils import plot_model
plot_model(model3,to_file='model3_plot.png',show_shapes=True, show_layer_names=True)

"""# **Todo :** Train your model"""

epochs = 30
#labels = tf.reshape(labels, (-1, 1))
## Your code goes here, use 30 epochs.
history = model3.fit(train_ds,epochs=epochs,validation_data=val_ds)

"""## **Todo :** Visualize the model results"""

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""## **Todo:** Analyze your results here. Did you get rid of underfitting/overfitting? Did class rebalance help?
Yes, overfitting is resolved, but validation accuracy is quite following training accuracy. Model is trained with dropout layers placed after 1st & 2nd Convolution layer and dense layer.

# To get better results, we add one more droput layer after 3rd convolution layer.
"""

## your code goes here
#Model

from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Rescaling, Conv2D, MaxPooling2D, Dropout, Flatten, Dense

# Define your input shape, e.g., (height, width, channels)
input_shape = (128, 128, 3)  # Replace with your actual input shape
class_names = ['class1', 'class2', 'class3']  # Replace with your actual class names

model3 = Sequential()

# Rescaling layer
model3.add(Rescaling(1./255, input_shape=input_shape))

# First Convolutional layer
model3.add(Conv2D(32, kernel_size=(2, 2), activation='relu'))
model3.add(MaxPooling2D(pool_size=(2, 2)))
model3.add(Dropout(0.25))

# Second Convolutional layer
model3.add(Conv2D(64, kernel_size=(2, 2), activation='relu'))
model3.add(MaxPooling2D(pool_size=(2, 2)))
model3.add(Dropout(0.25))

# Third Convolutional layer
model3.add(Conv2D(128, kernel_size=(2, 2), activation='relu'))
model3.add(MaxPooling2D(pool_size=(2, 2)))
model3.add(Dropout(0.25))

# Flattening
model3.add(Flatten())

# Dense Layer
model3.add(Dense(128, activation='relu'))
model3.add(Dropout(0.50))

# Output Layer
model3.add(Dense(len(class_names), activation='softmax'))

opt=tf.keras.optimizers.Adam()
model3.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),  # Use categorical crossentropy for multi-class classification
              optimizer=opt,
              metrics=['accuracy'],run_eagerly=True)

model3.summary()

from tensorflow.keras.utils import plot_model
plot_model(model3,to_file='model3_plot.png',show_shapes=True, show_layer_names=True)

from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Rescaling, Conv2D, MaxPooling2D, Dropout, Flatten, Dense

# Set correct input shape
input_shape = (180, 180, 3)
class_names = ['class1', 'class2', 'class3']  # Replace with actual class names

# Build the model
model3 = Sequential([
    Rescaling(1./255, input_shape=input_shape),

    Conv2D(32, (2, 2), activation='relu'),
    MaxPooling2D((2, 2)),
    Dropout(0.25),

    Conv2D(64, (2, 2), activation='relu'),
    MaxPooling2D((2, 2)),
    Dropout(0.25),

    Conv2D(128, (2, 2), activation='relu'),
    MaxPooling2D((2, 2)),
    Dropout(0.25),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),

    Dense(len(class_names), activation='softmax')
])

# Compile the model
model3.compile(optimizer='adam',
               loss='sparse_categorical_crossentropy',
               metrics=['accuracy'])

# Train the model
epochs = 30
history = model3.fit(train_ds, epochs=epochs, validation_data=val_ds)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

"""# Better training accuracy than last model.
# **Now, we will increase model complexity, by adding one convolution layer and dense layer.**
"""

## your code goes here
#Model
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Rescaling

# Define input shape
input_shape = (img_height, img_width, 3)

# Build the model
model3 = Sequential()

# Rescaling layer (corrected import)
model3.add(Rescaling(1./255, input_shape=input_shape))

# First Convolutional layer
model3.add(layers.Conv2D(32, kernel_size=(2,2), activation='relu'))
model3.add(layers.MaxPooling2D(pool_size=(2,2)))

# Second Convolutional layer
model3.add(layers.Conv2D(64, kernel_size=(2,2), activation='relu'))
model3.add(layers.MaxPooling2D(pool_size=(2,2)))

# Third Convolutional layer
model3.add(layers.Conv2D(128, kernel_size=(2,2), activation='relu'))
model3.add(layers.MaxPooling2D(pool_size=(2,2)))

# Fourth Convolutional layer
model3.add(layers.Conv2D(256, kernel_size=(2,2), activation='relu'))
model3.add(layers.MaxPooling2D(pool_size=(2,2)))

# Dropout
model3.add(layers.Dropout(0.5))

# Flatten
model3.add(layers.Flatten())

# Dense layers
model3.add(layers.Dense(256, activation='relu'))
model3.add(layers.Dropout(0.25))

model3.add(layers.Dense(128, activation='relu'))
model3.add(layers.Dropout(0.25))

model3.add(layers.Dense(64, activation='relu'))
model3.add(layers.Dropout(0.25))

# Output layer for 9 classes
model3.add(layers.Dense(9, activation='softmax'))

opt=tf.keras.optimizers.Adam()
model3.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),  # Use categorical crossentropy for multi-class classification
              optimizer=opt,
              metrics=['accuracy'],run_eagerly=True)

model3.summary()

from tensorflow.keras.utils import plot_model
plot_model(model3,to_file='model3_plot.png',show_shapes=True, show_layer_names=True)

epochs = 30
#labels = tf.reshape(labels, (-1, 1))
## Your code goes here, use 30 epochs.
history = model3.fit(train_ds,epochs=epochs,validation_data=val_ds)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(epochs)

plt.figure(figsize=(8, 8))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

import os

data_dir_test = '/content/drive/MyDrive/Colab_Notebooks/SkinCancer_ISIC_Data/Test'
class_names = sorted(os.listdir(data_dir_test))
print("Detected class names:", class_names)

"""# **We get rid of overfitting, Validation accuracy is following tarining accuracy.**"""

import os
import numpy as np
import matplotlib.pyplot as plt
from glob import glob
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# Select image path
test_class_index = 4
actual_class = class_names[test_class_index]

Test_image_path = os.path.join(data_dir_test, actual_class, '*')
Test_image_list = glob(Test_image_path)

if len(Test_image_list) == 0:
    print(f"No images found in {Test_image_path}")
else:
    # Use last available image
    image_path_to_use = Test_image_list[-1]

    # Load image
    test_image = load_img(image_path_to_use, target_size=(180, 180))  # ✅ fixed target size
    plt.imshow(test_image)
    plt.grid(False)
    plt.axis('off')
    plt.title("Test Image")
    plt.show()

    # Prepare image
    img_array = img_to_array(test_image)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    # ✅ Do not normalize if Rescaling is already in the model
    # If your model does not have Rescaling, uncomment the next line:
    # img_array = img_array / 255.0

    # Predict
    pred = model3.predict(img_array)
    pred_index = np.argmax(pred)
    pred_class = class_names[pred_index]

    print(f"Actual Class: {actual_class}")
    print(f"Predicted Class: {pred_class}")
    print(f"Confidence: {np.max(pred):.2f}")
